### ISSUE TITLE
rufus-scheduler incompatibility in rails 5.0

### ISSUE THREAD

**Issue by joaoBordalo** [jmettraux/rufus-scheduler#256]
Hi there,

I'm upgrading an app from rails 4.2.7 to 5.0.4.

I have updated the binary files through this command $rails app:update, and so far so good.

However, when i run this command  $rails db:migrate, I get the following error:

rails aborted!
NoMethodError: undefined method `scheduler' 

and the code it points is to this block in file config/initializers/scheduler.rb: (the **bold** is what is causing the error).

if !defined?(Rails::Console) && \
    File.basename($0) != 'rake' && \
    Rails.configuration.**scheduler**
  scheduler_pid_file = File.join(Rails.root, "tmp", "scheduler.pid").to_s
  Scheduler::start_unless_running scheduler_pid_file
end

I'm using gem 'rufus-scheduler', '~> 3.4.2'
And I followed this guide to upgrade: [here](https://hashrocket.com/blog/posts/how-to-upgrade-to-rails-5#3-update-rails-binaries-and-configurations)

Additionally, I tried to put rufus-scheduler(3.0.9) to the version that worked in rails 4.2.7. Still, no effect.

I believe this is an incompatibility with rails 5.0. Is there a way to solve this?

Thank you in advance,
João Bordalo

**Comment by jmettraux** [comment]
Hello,

* Could you please give the full error backtrace?
* Could you please also give the complete `config/initializers/scheduler.rb`?
* There is no mention of rufus-scheduler or scheduler in your guide at https://hashrocket.com/blog/posts/how-to-upgrade-to-rails-5#3-update-rails-binaries-and-configurations where did you get that `config/initializers/scheduler.rb`?
* What version of Ruby are you using?

> I believe this is an incompatibility with rails 5.0. Is there a way to solve this?

I would like to immediately set it straight that this has nothing to do with rufus-scheduler. The incompatibility lies in the Ruby-on-Rails configuration dealing with rufus-scheduler.

I will help you anyway. No worries.

**Comment by jmettraux** [comment]
Closing the issue, but not the conversation.

**Comment by joaoBordalo** [comment]
**Could you please give the full error backtrace?**
bin/rails db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rails aborted!
NoMethodError: undefined method `scheduler' for #<Rails::Application::Configuration:0x007fa3fe51f460>
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/railtie/configuration.rb:95:in `method_missing'
/home/clouduser/newrails5/project-control/config/initializers/scheduler.rb:122:in `<top (required)>'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:287:in `load'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:287:in `block in load'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:287:in `load'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/engine.rb:648:in `block in load_config_initializer'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.4/lib/active_support/notifications.rb:166:in `instrument'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/engine.rb:647:in `load_config_initializer'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/engine.rb:611:in `each'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/engine.rb:611:in `block in <class:Engine>'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/initializable.rb:30:in `instance_exec'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/initializable.rb:30:in `run'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/initializable.rb:44:in `each'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `call'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/initializable.rb:54:in `run_initializers'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/application.rb:352:in `initialize!'
/home/clouduser/newrails5/project-control/config/environment.rb:5:in `<top (required)>'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `block in require'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.4/lib/active_support/dependencies.rb:293:in `require'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/application.rb:328:in `require_environment!'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/clouduser/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.4/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate => environment


**Could you please also give the complete config/initializers/scheduler.rb?**
This file as sensitive information, so it is not recommended to give you the full file.


**There is no mention of rufus-scheduler or scheduler in your guide at https://hashrocket.com/blog/posts/how-to-upgrade-to-rails-5#3-update-rails-binaries-and-configurations where did you get that config/initializers/scheduler.rb?**

Yes, it doesn't say anything about rufus-scheduler. it was just a referrence for you to check what I have done. I got that error when i ran the command  rails db:migrate

**What version of Ruby are you using?**
2.3.0


Sorry for my miss understanding and thanks a lot for your time!

**Comment by jmettraux** [comment]
Hello João,

please try with this code:
```ruby
if (
  ! defined?(Rails::Console) &&
  File.basename($0) != 'rake' &&
  Rails.configuration.respond_to?(:scheduler)
) then
  scheduler_pid_file = File.join(Rails.root, 'tmp', 'scheduler.pid')
  Scheduler::start_unless_running(scheduler_pid_file)
end
```

It should schedule as usually, unless called from a Rake task.

Please tell me how it goes.

**Comment by joaoBordalo** [comment]
Wonderful!!! It Worked
Thank you so much!!

**Comment by jmettraux** [comment]
You're welcome, have a nice day!
